# Generated by Django 2.2 on 2020-01-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200130_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='person',
            new_name='owner',
        ),
    ]
