# Generated by Django 2.2 on 2020-01-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Subtitle')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('category', models.SmallIntegerField(choices=[(0, 'Article'), (1, 'News')], default=0, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
